from __future__ import annotations

from dngine.sdk.commands import CommandSpec, register_command_specs
from dngine.sdk.components import Action, Choice, FileList, Info, InfoCard, MetricDonut, MultiLine, Numeric, Output, Path, Preview, Row, Table, Text, TextPanel, TimerTask, Toggle
from dngine.sdk.documents import convert_docx_to_markdown, convert_markdown_to_docx, generate_output_filename, open_file_or_folder
from dngine.sdk.helpers import PayloadRequirement, before_task_run, build_runtime_payload, copy_to_clipboard, error_message, handle_task_error, handle_task_success, set_runtime_values, start_screen_picker, translated
from dngine.sdk.i18n import _pt, apply_direction, bind_tr, current_language, is_rtl, layout_direction, safe_tr, tr
from dngine.sdk.media import SUPPORTED_IMAGE_FILTER, apply_tag, pil_to_pixmap, safe_output_extension, solid_color_preview, transform_image
from dngine.sdk.menus import MenuActionSpec, attach_list_context_menu, attach_table_context_menu, show_context_menu
from dngine.sdk.plugin import AdvancedPagePlugin, BatchFilePlugin, DeclarativePlugin, HeadlessOnlyPlugin, StandardPlugin, TableToolPlugin, TaskPlugin
from dngine.sdk.specs import (
    ActionHandlerBindingSpec,
    ActionSpec,
    ChoiceOption,
    EnableRule,
    FieldSpec,
    FileListBehaviorSpec,
    PageSpec,
    PreviewBindingSpec,
    ResultSpec,
    SectionSpec,
    StateReactionSpec,
    StateSpec,
    TaskBindingSpec,
    TaskSpec,
    VisibilityRule,
)
from dngine.sdk.tasks import run_task_spec

Plugin = StandardPlugin

__all__ = [
    "_pt",
    "Action",
    "ActionHandlerBindingSpec",
    "ActionSpec",
    "AdvancedPagePlugin",
    "BatchFilePlugin",
    "Choice",
    "ChoiceOption",
    "CommandSpec",
    "DeclarativePlugin",
    "EnableRule",
    "FieldSpec",
    "FileList",
    "FileListBehaviorSpec",
    "HeadlessOnlyPlugin",
    "Info",
    "InfoCard",
    "MenuActionSpec",
    "MetricDonut",
    "MultiLine",
    "Numeric",
    "Output",
    "PayloadRequirement",
    "PageSpec",
    "Path",
    "Plugin",
    "Preview",
    "PreviewBindingSpec",
    "ResultSpec",
    "Row",
    "SectionSpec",
    "StateReactionSpec",
    "StateSpec",
    "StandardPlugin",
    "Table",
    "Text",
    "TextPanel",
    "Toggle",
    "TaskBindingSpec",
    "TableToolPlugin",
    "TaskPlugin",
    "TaskSpec",
    "TimerTask",
    "VisibilityRule",
    "apply_direction",
    "apply_tag",
    "attach_list_context_menu",
    "attach_table_context_menu",
    "before_task_run",
    "bind_tr",
    "build_runtime_payload",
    "error_message",
    "handle_task_error",
    "handle_task_success",
    "current_language",
    "convert_docx_to_markdown",
    "convert_markdown_to_docx",
    "copy_to_clipboard",
    "is_rtl",
    "layout_direction",
    "generate_output_filename",
    "open_file_or_folder",
    "pil_to_pixmap",
    "register_command_specs",
    "run_task_spec",
    "safe_tr",
    "safe_output_extension",
    "solid_color_preview",
    "set_runtime_values",
    "show_context_menu",
    "start_screen_picker",
    "SUPPORTED_IMAGE_FILTER",
    "transform_image",
    "translated",
    "tr",
]
